# Generated by Django 3.2.7 on 2021-09-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleAwareModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, default='', max_length=255, verbose_name='Sub Title')),
            ],
            options={
                'verbose_name': 'Example Aware Model',
                'verbose_name_plural': 'Example Aware Models',
            },
        ),
    ]
